name: ConvoyChat Setup Help
description: Need help setting up ConvoyChat? Open an issue.
title: "[SETUP HELP]:"
labels: ["setup", "help wanted"]
assignees:
  - C-EO
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: What do you need help with?
      description: Please state your issue here.
      placeholder: ex. 'Setting up environment variables.'
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: More Info
      description: Please provide more details.
      placeholder: I'm not quite familiar with setting up Auth0.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/c-eo/convoychat/blob/main/docs/code_of_conduct.md) and [Contributing Guidlines](https://github.com/c-eo/convoychat/blob/main/docs/contributing.md)
      options:
        - label: I agree to follow this project's **Code of Conduct** and **Contributing Guidlines**.
          required: true
        - label: I confirm that I searched for similar bug reports and found no relevant ones.
          required: true
        - label: I agree and confirm that all information provided by me is true and accurate.
          required: true
