name: Web Interface Bug Report
description: Found a bug with ConvoyChat's web interface? Report it here.
title: "[WEB INTERFACE BUG REPORT]:"
labels: ["bug", "ui/ux"]
assignees:
  - C-EO
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: ex. 'Site's contrast for `dark mode` doesn't conform to AAA standards.'
    validations:
      required: true
  - type: textarea
    id: browser
    attributes:
      label: Browser
      description: Please state your browser and its version below.
      placeholder: ex. Microsoft Edge - v107.0.1418.62 (Official build) (64-bit) 
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please upload any relevant screenshots below.      
      placeholder: TIP\:\ You can just drag and drop your screenshot here.
    validations:
      required: true
  - type: dropdown      
    id: reproduction
    attributes:
      label: Reproduction
      description: Can the bug be reproduced on our instance?
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/c-eo/convoychat/blob/main/docs/code_of_conduct.md) and [Contributing Guidlines](https://github.com/c-eo/convoychat/blob/main/docs/contributing.md)
      options:
        - label: I agree to follow this project's **Code of Conduct** and **Contributing Guidlines**.
          required: true
        - label: I confirm that I searched for similar bug reports and found no relevant ones.
          required: true
        - label: I agree and confirm that all information provided by me is true and accurate.
          required: true          